// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	AddUserServerStream(ctx context.Context, in *User, opts ...grpc.CallOption) (UserService_AddUserServerStreamClient, error)
	AddUserClientStream(ctx context.Context, opts ...grpc.CallOption) (UserService_AddUserClientStreamClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddUserServerStream(ctx context.Context, in *User, opts ...grpc.CallOption) (UserService_AddUserServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/pb.UserService/AddUserServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceAddUserServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_AddUserServerStreamClient interface {
	Recv() (*UserStream, error)
	grpc.ClientStream
}

type userServiceAddUserServerStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceAddUserServerStreamClient) Recv() (*UserStream, error) {
	m := new(UserStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) AddUserClientStream(ctx context.Context, opts ...grpc.CallOption) (UserService_AddUserClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/pb.UserService/AddUserClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceAddUserClientStreamClient{stream}
	return x, nil
}

type UserService_AddUserClientStreamClient interface {
	Send(*User) error
	CloseAndRecv() (*Users, error)
	grpc.ClientStream
}

type userServiceAddUserClientStreamClient struct {
	grpc.ClientStream
}

func (x *userServiceAddUserClientStreamClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userServiceAddUserClientStreamClient) CloseAndRecv() (*Users, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Users)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	AddUser(context.Context, *User) (*User, error)
	AddUserServerStream(*User, UserService_AddUserServerStreamServer) error
	AddUserClientStream(UserService_AddUserClientStreamServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) AddUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedUserServiceServer) AddUserServerStream(*User, UserService_AddUserServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AddUserServerStream not implemented")
}
func (UnimplementedUserServiceServer) AddUserClientStream(UserService_AddUserClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AddUserClientStream not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddUserServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(User)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).AddUserServerStream(m, &userServiceAddUserServerStreamServer{stream})
}

type UserService_AddUserServerStreamServer interface {
	Send(*UserStream) error
	grpc.ServerStream
}

type userServiceAddUserServerStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceAddUserServerStreamServer) Send(m *UserStream) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_AddUserClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).AddUserClientStream(&userServiceAddUserClientStreamServer{stream})
}

type UserService_AddUserClientStreamServer interface {
	SendAndClose(*Users) error
	Recv() (*User, error)
	grpc.ServerStream
}

type userServiceAddUserClientStreamServer struct {
	grpc.ServerStream
}

func (x *userServiceAddUserClientStreamServer) SendAndClose(m *Users) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userServiceAddUserClientStreamServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddUserServerStream",
			Handler:       _UserService_AddUserServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddUserClientStream",
			Handler:       _UserService_AddUserClientStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
